// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("browser.search.suggest.enabled", false);
user_pref("browser.startup.homepage", "google.com");
user_pref("browser.tabs.warnOnClose", true);
user_pref("browser.toolbars.bookmarks.visibility", "always");
user_pref("browser.translations.mostRecentTargetLanguages", "ja,en,zh-Hans");
user_pref("browser.translations.panelShown", true);
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.scenario", "offline");
user_pref("browser.urlbar.showSearchTerms.enabled", false);
user_pref("browser.urlbar.suggest.history", false);
user_pref("browser.urlbar.suggest.quicksuggest.nonsponsored", true);
user_pref("browser.urlbar.suggest.quicksuggest.sponsored", false);
user_pref("browser.urlbar.suggest.recentsearches", false);
user_pref("browser.urlbar.suggest.searches", false);
user_pref("browser.urlbar.suggest.topsites", false);
user_pref("devtools.cache.disabled", true);
user_pref("devtools.editor.keymap", "emacs");
user_pref("services.sync.username", "zhichen0428@gmail.com");
user_pref("ui.key.accelKey", 91);
